version: '3'

services:

  subquery-node-moonbeam-balance-v2:
    image: onfinality/subql-node:v1.14.1
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS:  
      DB_DATABASE: prod-moonbeam-balance
      DB_HOST: 
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=public
      - --scale-batch-size=true
      - --batch-size=10

