specVersion: 0.2.0
description: 'Moonbeam balance and activities indexer'
repository: 'https://github.com/web3go-xyz/moonbeam-balance-indexer.git'
schema: 
  file: ./schema.graphql
network:
  endpoint: wss://moonbeam.api.onfinality.io/public-ws
  genesisHash: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1   
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        # - handler: handleEvent
        #   kind: substrate/EventHandler

