specVersion: 0.2.0
description: ''
repository: ''
schema: 
  file: ./schema.graphql
network:
  endpoint: wss://moonbeam.api.onfinality.io/public-ws
  genesisHash: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1  # 7560558   7560585 7560724
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        # - handler: handleEvent
        #   kind: substrate/EventHandler
      #handlers:
      #  - handler: handleTransfer
      #    kind: substrate/EventHandler
      #    filter:
      #      module: balances
      #      method: Transfer
